apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service-deployment
  namespace: ashok
  labels:
    app: customers-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers-service
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      containers:
        - name: customers-service
          image: caannamalai/customerserver:1.0.0
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
  namespace: ashok
  labels:
    app: customers-service
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: customers-service
